$schema: "https://json-schema.org/draft/2020-12/schema"
description: an entry in the sample sheet
properties:
  sample:
    type: string
    description: sample name/identifier
  condition:
    type: string
    description: sample condition that will be compared during differential analysis
  replicate:
    type: number
    default: 1
    description: consecutive numbers representing multiple replicates of one condition
  fq1:
    type: string
    description: path to fastq file

required:
  - sample
  - condition
  - replicate
  - fq1
