$schema: "http://json-schema.org/draft-07/schema#"
description: an entry in the sample sheet
properties:
  sample:
    type: string
    description: sample name/identifier
  condition:
    type: string
    description: sample condition that will be compared during differential analysis
  replicate:
    type: number
    default: 1
    description: consecutive numbers representing multiple replicates of one condition
  lib_prep:
    type: string
    default: "None"
    description: type of library preparation; optional
  data_folder:
    type: string
    description: path to fastq files
  fq1:
    type: string
    description: names of fastq files

required:
  - sample
  - condition
  - replicate
  - data_folder
  - fq1
